---
title: "Pennie_Data_Thesis"
author: "Karen Ornelas"
date: "1/30/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
## Read Pennie's  .csv into R as an object
library(readr)
library(tidyverse)
Pennie_df <- read_csv("Pennie_Clean_Data")
```

```{r}
## Add a DOY into the original Pennie_df to help with finding first flower data later
library(lubridate)
Pennie_df <- Pennie_df %>%
  mutate(DOY = yday(Pennie_df$Observation_date))

## Add a year columun to help with later calcuations to find ff
Pennie_df <- Pennie_df %>%
  mutate(Year = 
    str_extract(Observation_date,"^.{4}"))
```


```{r}
##see if you can remove year from data on pennie df
library(stringr)
Pennie_Timeline_df <- Pennie_df[c("Scientific_name","Observation_date")]

Pennie_Timeline_df <- Pennie_Timeline_df %>%
  mutate(Year = 
    str_extract(Observation_date,"^.{4}"))

Pennie_Timeline_df <- Pennie_Timeline_df[-c(2)]

```


```{r}
## Create new dataframe DO WE NEED THIS?
Pennie_Timeline_df_Pennie_Mean_plot <- Pennie_Timeline_df %>%
  distinct(Year,Scientific_name, .keep_all = TRUE)

```


```{r}
Pennie_Timeline_df_unique_species <-  Pennie_Timeline_df %>% 
  group_by(Scientific_name) %>%
  count()

```


```{r}
## do same process but filter where pheno =  start 
Pennie_Timeline_Start <- Pennie_df %>% 
  filter(Pheno == "Start") %>% 
  mutate(Year = str_extract(Observation_date,"^.{4}"),
         Year = as.numeric(Year),
        DOY = yday(Observation_date)) 
```

```{r}
## We need to find a benchmark year in Pennie's data where all species are accounted for
Pennie_Timeline_benchmark <-  Pennie_df %>% 
  group_by(Year) %>%
  count()

```


```{r}
## use the benchmark species to find the average doy for bechmark
## is there a better way to do this
Pennie_Benchmark_Species <- Pennie_df %>%
  filter(Year == "1970", Pheno == "Start" ) %>%
  group_by(Scientific_name) %>%
  mutate(Mean_FF_Date = DOY) |> 
  filter(Scientific_name != "Eupatorium rugosum")


```


```{r}
# Creating a DF with species that have at least 10 records of observation to then be compared the benchmark species 

Pennie_Timeline_df_10 <- Pennie_Timeline_df_unique_species %>% 
  filter(n >= 10)

Pennie_per_Year_10 <- semi_join(Pennie_Timeline_Start, Pennie_Timeline_df_10) %>%
  group_by(Year) %>%
  count()

Pennie_Benchmark_10 <- semi_join(Pennie_Benchmark_Species, Pennie_Timeline_df_10)
```

```{r}
## Subtract the DOY from each species from doy of benchmark_mean = FFD

# Perform the subtraction and store the result in pennie_benchmark_mean
FFD_df <- Pennie_Timeline_Start %>%
  inner_join(Pennie_Benchmark_10, by = "Scientific_name", suffix = c("_pennie", "_benchmark"))   %>%
  mutate(FFD = DOY_pennie - DOY_benchmark) %>%
  select(Scientific_name, Year_pennie, DOY_pennie, DOY_benchmark, FFD)

# Find the average FFD by year within the FFD_df
FFD_mean_year <- FFD_df %>%
  group_by(Year_pennie) %>%
  summarize(mean_FFD = mean(FFD))
```

Plot FFD 
```{r}
ggplot(FFD_mean_year, aes(Year_pennie, mean_FFD)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_bw()

summary(lm(FFD_mean_year$mean_FFD ~ FFD_mean_year$Year_pennie))
```


## Blue Hill Observatory Weather Data

```{r}
# read in data
weather <- read_csv("BlueHillObservatory_Temperature_Mean_2828_Monthly_v2.4.csv", skip = 4, col_names = TRUE) |> 
  select(Year:December) |> 
  drop_na()
```
Get data in long format
```{r}
weather_long <- weather |> 
  pivot_longer(January:December,
               names_to = "Month",
               values_to = "Avg_Temp")
weather_long

#write_csv(weather_long, "BlueHill_weather_long.csv")
```

### Combine BH Weather and FFD

```{r}
FFD_weather <- left_join(FFD_df, weather, join_by(Year_pennie == Year)) |> 
  filter(FFD >= -30, FFD <= 30)
```

Check FFD that are above 25
```{r}
# FFD_weather |> 
#   filter(FFD > 25)
# 
# FFD_weather |> 
#   filter(Scientific_name == "Eupatorium rugosum")
```


### Early Flowering Species

Plot start dates for only species with >= 10 years of data
```{r}
Pennie_Start <-  Pennie_Timeline_Start |> 
  group_by(Scientific_name) |> 
  count()

ggplot(Pennie_Start, aes(n)) +
  geom_histogram()

Pennie_Start_10 <- Pennie_Timeline_Start |> 
  group_by(Scientific_name) |> 
  count() |> 
  filter(n >= 10)

start_10years <- semi_join(Pennie_Timeline_Start, Pennie_Start_10)

start_10years |> group_by(Scientific_name) |> count()

ggplot(start_10years, aes(x = Year, y = DOY)) +
  geom_point()

ggplot(start_10years, aes(x = Year, y = DOY, color = Scientific_name)) +
  geom_point()
```

Species that flower by the end of May at least once in the dataset

```{r}
pre_june_species <- start_10years |> 
  filter(DOY <= 152) |> 
  distinct(Scientific_name)

start_10years_prejune <- semi_join(start_10years, pre_june_species) |> 
  filter(DOY < 250)

# number of data points per species
start_10years_prejune |> group_by(Scientific_name) |> count()

# how many species per year
start_10years_prejune |> group_by(Year) |> count()

ggplot(start_10years_prejune, aes(x = Year, y = DOY)) +
  geom_point(aes(color = Scientific_name)) +
  geom_smooth(method = "lm")

# species in reference year
early_species_1970 <- start_10years_prejune |> 
  filter(Year == 1970) |> 
  distinct()

# how many years of data for species in 1970
prejune_10years_1970 <- semi_join(start_10years_prejune, early_species_1970, join_by(Scientific_name)) 

ggplot(prejune_10years_1970, aes(x = Year, y = DOY)) +
  geom_point(aes(color = Scientific_name)) +
  geom_smooth(method = "lm")
```


```{r}
# Redoing all the code to now use the prejune species as the benchmark 
# Rerunning all the ggplots with the new object
## Subtract the DOY from each species from doy of benchmark_mean = FFD

# Perform the subtraction and store the result in pennie_benchmark_mean
prejune_FFD_df <- prejune_10years_1970 %>%
  inner_join(early_species_1970, 
             by = "Scientific_name", suffix = c("_prejune", "_benchmark"))  %>%
  mutate(FFD = DOY_prejune - DOY_benchmark) %>%
  select(Scientific_name, Year_prejune, DOY_prejune, DOY_benchmark, FFD)

# Find the average FFD by year within the prejune_FFD_df
prejune_FFD_mean_year <- prejune_FFD_df %>%
  group_by(Year_prejune) %>%
  summarize(mean_FFD = mean(FFD))
```

Plot FFD 
```{r}
prejune_meanFFD_plot <- ggplot(prejune_FFD_mean_year, aes(Year_prejune, mean_FFD)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_bw()

ggsave("Prejune_Mean_FFD_Plot.png", prejune_meanFFD_plot)

summary(lm(prejune_FFD_mean_year$mean_FFD ~ prejune_FFD_mean_year$Year_prejune))

```

### Combine BH Weather and FFD

```{r}
Prejune_FFD_weather <- left_join(prejune_FFD_df, weather, join_by(Year_prejune == Year)) |> 
  filter(FFD >= -30, FFD <= 30)
```


```{r}
Prejune_FFD_Jan_Plot <- ggplot(Prejune_FFD_weather, aes(FFD, January)) +
  geom_point() +
  geom_smooth(method = "lm")

ggsave("Prejune_FFD_Jan.png", Prejune_FFD_Jan_Plot)

jan_lm <- lm(FFD ~ January, data = Prejune_FFD_weather)
summary(jan_lm)
```

```{r}
Prejune_FFD_Feb_Plot <- ggplot(Prejune_FFD_weather, aes(FFD, February)) +
  geom_point() +
  geom_smooth(method = "lm")

ggsave("Prejune_FFD_Feb.png", Prejune_FFD_Feb_Plot)

feb_lm <- lm(FFD ~ February, data = Prejune_FFD_weather)
summary(feb_lm)
```
March

```{r}
Prejune_FFD_Mar_Plot <- ggplot(Prejune_FFD_weather, aes(FFD, March)) +
  geom_point() +
  geom_smooth(method = "lm")

ggsave("Prejune_FFD_Mar.png", Prejune_FFD_Mar_Plot)

march_lm <- lm(FFD ~ March, data = Prejune_FFD_weather)
summary(march_lm)
```

April
```{r}
Prejune_FFD_Apr_Plot <- ggplot(Prejune_FFD_weather, aes(FFD, April)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

ggsave("Prejune_FFD_Apr.png", Prejune_FFD_Mar_Plot)

april_lm <- lm(FFD ~ April, data = Prejune_FFD_weather)
summary(april_lm)
```

May
```{r}
Prejune_FFD_May_Plot <- ggplot(Prejune_FFD_weather, aes(FFD, May)) +
  geom_point() +
  geom_smooth(method = "lm")

ggsave("Prejune_FFD_May.png", Prejune_FFD_May_Plot)

may_lm <- lm(FFD ~ May, data = Prejune_FFD_weather)
summary(may_lm)
```


```{r}
Prejune_FFD_weather %>%
  summarise(avg_doy = mean(DOY_prejune))
```
as